from . import _NegativeSampler
import torch
from typing import Dict

class UniformSamplerWithReplacement(_NegativeSampler):
    r"""UniformSamplerWithReplacement is to generate negative samplers by uniform distribution with replacement, i.e. draw samples uniformlly with replacement
    """
    @staticmethod
    def _getlen(kwargs: Dict[str, Dict[str, int]]) -> Dict[str, int]:
        r"""Get length of field.
        
        Args:
            kwargs (Dict[str, Dict[str, int]]): kwargs
        
        Returns:
            int: Length of field.
        """
        return {k: v["high"] - v["low"] for k, v in kwargs}

    @staticmethod
    def _generate(**kwargs: Dict[str, int]) -> torch.Tensor:
        r"""A function to generate negative samples with uniform distribution with replacement.
        
        Arguments:
            low (int): Lowest integer to be drawn from the distribution.
            high (int): One above the highest integer to be drawn from the distribution.
            size (int): An integer defining the shape of the output tensor.
        
        Returns:
            T, shape = (N * Nneg, 1), dtype = torch.long: Tensor of negative samples generated by uniform distribution.
        """
        return torch.randint(low=kwargs["low"], high=kwargs["high"], size=(kwargs["size"], 1)).long()


class UniformSamplerWithoutReplacement(_NegativeSampler):
    r"""UniformSamplerWithReplacement is to generate negative samplers by uniform distribution without replacement, i.e. draw samples uniformlly without replacement
    """
    @staticmethod
    def _getlen(kwargs: Dict[str, Dict[str, int]]) -> Dict[str, int]:
        r"""Get length of field.
        
        Args:
            kwargs (Dict[str, Dict[str, int]]): kwargs
        
        Returns:
            int: Length of field.
        """
        return {k: v["high"] - v["low"] for k, v in kwargs}

    @staticmethod
    def _generate(**kwargs: Dict[str, int]) -> torch.Tensor:
        r"""A function to generate negative samples with uniform distribution without replacement.
        
        Arguments:
            low (int): minimum value (i.e. lower bound) of sampling id.
            high (int): maximum value (i.e. upper bound) of sampling id.
            size (int): An integer of defining the shape of the output tensor.
        
        Returns:
            T, shape = (N * Nneg, 1), dtype = torch.long: Tensor of negative samples generated by uniform distribution.
        """
        samples = torch.randperm(n=kwargs["high"]) + kwargs["low"]
        samples = samples[:kwargs["size"]]
        return samples.view(-1, 1)
