r"""torecsys.layers.ctr is a sub module of implementation of layers in click through rate prediction.
"""

from .attentional_factorization_machine import AttentionalFactorizationMachineLayer
from .bias_encoding import BiasEncodingLayer
from .bilinear import BilinearNetworkLayer
from .bilinear_interaction import BilinearInteractionLayer
from .compose_excitation_network import ComposeExcitationNetworkLayer
from .compress_interaction_network import CompressInteractionNetworkLayer
from .cross_network import CrossNetworkLayer
from .dynamic_routing import DynamicRoutingLayer
from .factorization_machine import FactorizationMachineLayer
from .field_aware_factorization_machine import FieldAwareFactorizationMachineLayer
from .inner_product_network import InnerProductNetworkLayer
from .mixture_of_experts import MixtureOfExpertsLayer
from .multilayer_perceptron import MultilayerPerceptronLayer
from .outer_product_network import OuterProductNetworkLayer
from .positon_bias_aware_learning_framework import PositionBiasAwareLearningFrameworkLayer
from .position_embedding import PositionEmbeddingLayer
from .wide import WideLayer

# create shorten name of layers
SqueezeAndExcitationNetworkLayer = ComposeExcitationNetworkLayer

AFMLayer = AttentionalFactorizationMachineLayer
CENLayer = ComposeExcitationNetworkLayer
CINLayer = CompressInteractionNetworkLayer
DenseLayer = MultilayerPerceptronLayer
DNNLayer = MultilayerPerceptronLayer
FFMLayer = FieldAwareFactorizationMachineLayer
FMLayer = FactorizationMachineLayer
FullyConnectLayer = MultilayerPerceptronLayer
FeedForwardLayer = MultilayerPerceptronLayer
MOELayer = MixtureOfExpertsLayer
PALLayer = PositionBiasAwareLearningFrameworkLayer
SENETLayer = SqueezeAndExcitationNetworkLayer

